#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in2,    pExpander,      sensorAnalog)
#pragma config(Sensor, in3,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  lftSolenoid,    sensorDigitalOut)
#pragma config(Sensor, dgtl2,  rtSolenoid,     sensorDigitalOut)
#pragma config(Sensor, dgtl6,  limit,          sensorTouch)
#pragma config(Sensor, dgtl7,  backRightSonar, sensorSONAR_mm)
#pragma config(Sensor, dgtl9,  backLeftSonar,  sensorSONAR_mm)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_4,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           frtlftdrive,   tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port2,           tparms,        tmotorVex393, openLoop)
#pragma config(Motor,  port3,           btlftarm,      tmotorVex393, openLoop, encoder, encoderPort, I2C_3, 1000)
#pragma config(Motor,  port4,           btrtarm,       tmotorVex393, openLoop, encoder, encoderPort, I2C_2, 1000)
#pragma config(Motor,  port6,           intk,          tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port7,           intk2,         tmotorVex393HighSpeed, openLoop, reversed)
#pragma config(Motor,  port8,           btrtdrive,     tmotorVex393, openLoop, encoder, encoderPort, I2C_1, 1000)
#pragma config(Motor,  port9,           btlftdrive,    tmotorVex393, openLoop, encoder, encoderPort, I2C_4, 1000)
#pragma config(Motor,  port10,          frtrtdrive,    tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!
#include "Constants.h"
#include "UltrasonicFunctions.h"
#include "Menu.h"
#include "subsystems/ArmControls.h"
#include "subsystems/DriveControls.h"
#include "subsystems/Manipulator.h"
#include "Autonomii.h"

//TODO make recorded auton
/*
The whole idea is to have a limited driver control - have a driveforwardPID function, a turnAtSpeedPID function, Lift function,
intake function. Have it record every time a task has been completed.
*/

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////
void pre_auton()
{
  PIDreset();
  //Turn on LCD Backlight
  bLCDBacklight = true;
  bStopTasksBetweenModes = false;
  displayLCDCenteredString(0,"Calibrating...");
  displayLCDCenteredString(1,"Please Wait");
  wait1Msec(2000);
  StartTask(Menu);
  StartTask(updateSonarValues);
}

///////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////
task autonomous()
{
	//StopTask(Menu);
	switch(count) {
	  case 0: {
      autonomous0();
      break;
	  }
	  case 1: {
	    autonomous1();
	    break;
	  }
	  case 2: {
      autonomous2();
      break;
	  }
	  case 3: {
      autonomous3();
      break;
	  }
	  case 4:{
      programming();
      break;
	  }
  }
}
/////////////////////////////////////////////////////////////////////////////////////////+
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	//Reset the encoders
	StopTask(autonomous);
	nMotorEncoder[btlftarm]=0;
	bLCDBacklight = true;
	while (true)
	{
		gyroo = gyroValue();
		driveOpControlComp();
		armControlOpComp();
		intakeControlOpComp();
	  //Try to auto-descore height with roller already in
	  if (vexRT[Btn8D]==1&&vexRT[Btn6D]==0&&vexRT[Btn6U]==0)
		{
			savedPosition = true;
			position = 250;
			SensorValue[lftSolenoid]=1;
		  SensorValue[rtSolenoid]=1;
		  motor[intk]=127;
			motor[intk2]=127;
	  }

	  //User-reset the motor encoders
	  if (vexRT[Btn8R]==1){
	  	nMotorEncoder[btlftarm]=0;
	  }
	}
}
